// =========================
// DEPENDENCY-FREE XML WELL-FORMEDNESS CHECK
// The syndication feed is generated by hand, so it is validated before it is
// served (and reported on the admin syndication page) instead of waiting for an
// aggregator to reject it. This covers the failures a hand-built feed actually
// produces: unbalanced elements, raw markup characters that escaped encoding,
// broken CDATA and characters XML 1.0 forbids outright.
// =========================

// XML 1.0 allows tab, LF, CR and everything from #x20 up, minus the
// surrogate/noncharacter blocks. Anything else (e.g. #x0B, #x0C, #x1F pasted
// from Word) makes the whole document unparseable.
const INVALID_CHARS = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\uFFFE\uFFFF]/g;

const NAME = "[A-Za-z_:][\\w.:-]*";
const ENTITY = /^&(#\d+|#x[0-9A-Fa-f]+|amp|lt|gt|quot|apos);/;

const stripInvalidChars = (value) =>
  String(value === null || value === undefined ? "" : value).replace(
    INVALID_CHARS,
    ""
  );

const lineOf = (xml, index) => xml.slice(0, index).split("\n").length;

const validateXml = (xml) => {
  const errors = [];
  const text = String(xml || "");

  if (!text.trim()) return { valid: false, errors: ["Document is empty"] };

  const invalid = text.match(INVALID_CHARS);
  if (invalid) {
    const codes = [...new Set(invalid.map((c) => c.charCodeAt(0)))]
      .map((c) => `0x${c.toString(16)}`)
      .join(", ");
    errors.push(`Contains characters XML 1.0 forbids: ${codes}`);
  }

  const stack = [];
  let roots = 0;
  let i = 0;

  while (i < text.length) {
    const next = text.indexOf("<", i);

    if (next === -1) {
      validateText(text.slice(i), i);
      break;
    }

    validateText(text.slice(i, next), i);

    if (text.startsWith("<!--", next)) {
      const end = text.indexOf("-->", next);
      if (end === -1) {
        errors.push(`Unterminated comment at line ${lineOf(text, next)}`);
        break;
      }
      i = end + 3;
      continue;
    }

    if (text.startsWith("<![CDATA[", next)) {
      const end = text.indexOf("]]>", next);
      if (end === -1) {
        errors.push(`Unterminated CDATA at line ${lineOf(text, next)}`);
        break;
      }
      if (!stack.length) {
        errors.push(`CDATA outside of an element at line ${lineOf(text, next)}`);
      }
      i = end + 3;
      continue;
    }

    if (text.startsWith("<?", next) || text.startsWith("<!", next)) {
      const end = text.indexOf(">", next);
      if (end === -1) {
        errors.push(
          `Unterminated processing instruction at line ${lineOf(text, next)}`
        );
        break;
      }
      i = end + 1;
      continue;
    }

    const end = text.indexOf(">", next);
    if (end === -1) {
      errors.push(`Unterminated tag at line ${lineOf(text, next)}`);
      break;
    }

    const inner = text.slice(next + 1, end);
    i = end + 1;

    if (inner.startsWith("/")) {
      const name = inner.slice(1).trim();
      const open = stack.pop();
      if (!open) {
        errors.push(
          `Closing </${name}> with no open element at line ${lineOf(text, next)}`
        );
      } else if (open !== name) {
        errors.push(
          `Closing </${name}> does not match <${open}> at line ${lineOf(text, next)}`
        );
      }
      continue;
    }

    const selfClosing = inner.endsWith("/");
    const name = (selfClosing ? inner.slice(0, -1) : inner).trim().split(/\s/)[0];

    if (!new RegExp(`^${NAME}$`).test(name)) {
      errors.push(`Invalid element name "${name}" at line ${lineOf(text, next)}`);
      continue;
    }

    if (!stack.length && !selfClosing) roots += 1;
    if (!selfClosing) stack.push(name);
  }

  if (stack.length) {
    errors.push(`Unclosed element(s): ${[...new Set(stack)].join(", ")}`);
  }

  if (roots > 1) errors.push(`Document has ${roots} root elements, expected 1`);
  if (roots === 0 && !errors.length) errors.push("Document has no root element");

  return { valid: errors.length === 0, errors };

  // Character data outside CDATA has to be encoded: a stray "&" or "<" is the
  // classic way a job description breaks a feed.
  function validateText(chunk, offset) {
    if (!chunk) return;

    let cursor = chunk.indexOf("&");
    while (cursor !== -1) {
      if (!ENTITY.test(chunk.slice(cursor))) {
        errors.push(
          `Unescaped "&" at line ${lineOf(text, offset + cursor)}`
        );
        break;
      }
      cursor = chunk.indexOf("&", cursor + 1);
    }
  }
};

module.exports = { validateXml, stripInvalidChars, INVALID_CHARS };
